### PR TITLE
Added team commendations to sent/received page

### LINKED ISSUE #159: Team Commendation Sent/Received
When a Team Commendation is sent and/or received, it should appear in the `me/sent/[email]` and `me/received/[email]` page.

### PR DESCRIPTION
**Pull request by ashlyndevries**
Closes #159

### CODE REVIEW

**Comment by SpBills** [comment]
Looks generally okay, but you need to fix an issue where:

image


for some reason on my sent page I get a 404. I think it is because of this line:

image

**Comment by SebastianNeiswanger** [comment]
> Looks generally okay, but you need to fix an issue where:
> 
> 
> 
> image
> 
> 
> 
> 
> 
> for some reason on my sent page I get a 404. I think it is because of this line:
> 
> 
> 
> image
> 
> 

This happened during testing as well, and we beloved the same thing. It only happens if there is nothing to be found for the page. Would you rather we have a <Nothing/> component.

**Comment by SpBills** [comment]
> 

Yes Please

**Comment by SpBills** [comment]
@SebastianNeiswanger

**Review by SpBills — CHANGES_REQUESTED** [review]
Please fix bug described

**Comment by SebastianNeiswanger** [comment]
I plan to get to this tomorrow.

**Comment by SebastianNeiswanger** [comment]
This is what the pages look like with no commendations.  
image

**Comment by SebastianNeiswanger** [comment]
@ashlyndevries I approve of what you've done. Can you check the changes I made, including the comment above, and merge if all looks good?

**Review by SpBills — APPROVED** [review]
LGTM

**Comment by SpBills** [comment]
@ashlyndevries Please fix merge conflicts.

**Pull request merged**
